# Generated by Django 3.2 on 2024-08-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=256, verbose_name='Код поддтверждения'),
        ),
    ]
